### ISSUE TITLE
Included third-party dependencies should be properly cited

### ISSUE THREAD

**Issue by sarasafavi** [boundlessgeo/django-osgeo-importer#3]
e.g., https://github.com/boundlessgeo/django-osgeo-importer/blob/master/osgeo_importer/static/osgeo_importer/css/angular-wizard.min.css

is taken from https://github.com/angular-wizard/angular-wizard/blob/master/dist/angular-wizard.min.css. 

Vendoring this in is acceptable [per the original author](https://github.com/angular-wizard/angular-wizard/blob/master/README.md) but  at minimum `angular-wizard`'s [MIT license](https://github.com/angular-wizard/angular-wizard/blob/master/license.md) must be respected, including copyright notice.

**Comment by sarasafavi** [comment]
With https://github.com/boundlessgeo/django-osgeo-importer/pull/7 in, this is now irrelevant

**Comment by ghost** [comment]
Yes, while IANAL I think that referencing the project on npm should be sufficient especially if the author's own doc says this is an OK usage
