### ISSUE TITLE
instead of committing minified deps, automate and document build process as part of install

### ISSUE THREAD

**Issue by ghost** [boundlessgeo/django-osgeo-importer#4]
I think it's a mess to include angular wizard in minified form in the repo.

referring to the build of static assets that make up the JS front end.

**Comment by sarasafavi** [comment]
Agree 100%. This would likely also take care of https://github.com/boundlessgeo/django-osgeo-importer/issues/3

**Comment by ghost** [comment]
package.json seems pretty useless, I guess they were downloading minified angular and just checking it into the repo?

**Comment by sarasafavi** [comment]
Fixed in #7

**Comment by ghost** [comment]
Decided not to require any frontend steps for an install, it seems counterproductive for a django app and I would prefer to avoid forcing the usage of any particular asset management strategy since django projects that might want this will use whatever they want to.
