### ISSUE TITLE
Review package.json

### ISSUE THREAD

**Issue by ghost** [boundlessgeo/django-osgeo-importer#5]
Existing package.json seems to be purely copypasta from https://github.com/lorem--ipsum/smashing-article/blob/master/package.json

It's likely some of that is not quite suitable for us and at minimum we should update metadata not to point at the lorem--ipsum repo URL, it just looks sloppy.

**Comment by sarasafavi** [comment]
Fixed in https://github.com/boundlessgeo/django-osgeo-importer/pull/6
